apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: nginx-dev
  source:
    path: dev-env/nginx
    repoURL: https://github.com/DevOps-Study-Stuff/for-testing
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
