---
apiVersion: v1https://github.com/DevOps-Study-Stuff/for-testing/edit/main/dev-env/nginx-dev/nginx-dev.yaml
kind: Namespace
metadata:
  name: nginx-dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-dev
  template:
    metadata:
      labels:
        app: nginx-dev
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-dev-service
  namespace: nginx-dev
spec:
  type: NodePort
  selector:
    app: nginx-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
